name: Generate AST and Flowchart (REST)

on:
  repository_dispatch:
    types: [generate-ast-flowchart]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Print parameters
        run: |
      - name: Print parameters
        run: |
          echo "Program Name: ${{ github.event.inputs.programName }}"
          echo "Source Directory: ${{ github.event.inputs.srcDir }}"
          echo "Copybooks Directory: ${{ github.event.inputs.copyBooksDir }}"
          echo "Report Directory: ${{ github.event.inputs.reportDir }}"
          echo "Flowchart Generation Strategy: ${{ github.event.inputs.generation }}"
          echo "Dialect: ${{ github.event.inputs.dialect }}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Install Graphviz
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install -y python3-pydot graphviz
      - name: Checkout Cobol sources
        run: |
          git clone https://github.com/neopragma/cobol-samples.git
      - name: Run AST generation
        uses: ./.github/workflows/actions/run-ast-generation
        with:
          programName: ${{ github.event.inputs.programName }}
          srcDir: ${{ github.event.inputs.srcDir }}
          copyBooksDir: ${{ github.event.inputs.copyBooksDir }}
          reportDir: ${{ github.event.inputs.reportDir }}
          generation: PROGRAM
          dialect: COBOL
