name: Generate AST and Flowchart (UI)

on:
  workflow_dispatch:
    inputs:
      programName:
        description: "Cobol program name"
        required: true
        default: test-exp.cbl

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v2
      - name: Print parameters
        run: |
          echo "Program Name: ${{ github.event.inputs.programName }}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Install Graphviz
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install -y python3-pydot graphviz
      - name: Checkout Cobol sources
        run: |
          git clone https://github.com/neopragma/cobol-samples.git
      - name: Run AST generation
        uses: ./.github/workflows/actions/run-ast-generation
        with:
          programName: ${{ github.event.inputs.programName }}"
