# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Checkout submodules
      # You may pin to the exact commit or the version.
      # uses: textbook/git-checkout-submodule-action@0cb23c7e6a67085e1dc5e884920bd620f7b9c469
      uses: textbook/git-checkout-submodule-action@2.1.1
      with:
        # Set the --remote flag
        remote: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # - name: Publish to GitHub Packages Apache Maven
      # run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      # env:
        # GITHUB_TOKEN: ${{ github.token }}
